# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 5.24
    has_acceleration_limits: true
    max_acceleration: 1.048
  joint_2:
    has_velocity_limits: true
    max_velocity: 5.59
    has_acceleration_limits: true
    max_acceleration: 1.118
  joint_3:
    has_velocity_limits: true
    max_velocity: 5.59
    has_acceleration_limits: true
    max_acceleration: 1.118
  joint_4:
    has_velocity_limits: true
    max_velocity: 6.28
    has_acceleration_limits: true
    max_acceleration: 1.256
  joint_5:
    has_velocity_limits: true
    max_velocity: 20.94
    has_acceleration_limits: true
    max_acceleration: 4.188