# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 3.67
    has_acceleration_limits: true
    max_acceleration: 0.734
  joint_2:
    has_velocity_limits: true
    max_velocity: 3.32
    has_acceleration_limits: true
    max_acceleration: 0.664
  joint_3:
    has_velocity_limits: true
    max_velocity: 3.67
    has_acceleration_limits: true
    max_acceleration: 0.734
  joint_4:
    has_velocity_limits: true
    max_velocity: 6.98
    has_acceleration_limits: true
    max_acceleration: 1.396
  joint_5:
    has_velocity_limits: true
    max_velocity: 6.98
    has_acceleration_limits: true
    max_acceleration: 1.396
  joint_6:
    has_velocity_limits: true
    max_velocity: 10.47
    has_acceleration_limits: true
    max_acceleration: 2.094