# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_1:
    has_acceleration_limits: true
    has_velocity_limits: true
    max_acceleration: 0.628
    max_velocity: 3.14
  joint_2:
    has_acceleration_limits: true
    has_velocity_limits: true
    max_acceleration: 0.628
    max_velocity: 3.14
  joint_3:
    has_acceleration_limits: true
    has_velocity_limits: true
    max_acceleration: 0.786
    max_velocity: 3.93
  joint_4:
    has_acceleration_limits: true
    has_velocity_limits: true
    max_acceleration: 1.396
    max_velocity: 6.98
  joint_5:
    has_acceleration_limits: true
    has_velocity_limits: true
    max_acceleration: 1.152
    max_velocity: 5.76
  joint_6:
    has_acceleration_limits: true
    has_velocity_limits: true
    max_acceleration: 1.676
    max_velocity: 8.38
